# Setup
title:               resigning in sente
tagline:             'a baduk/weiqi/go strategy blog'
description:         'A blog devoted to baduk/weiqi/go strategy discussions aimed at kyu-level players.'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty
future:              true        ''

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
